# Generated by Django 5.0.5 on 2024-05-08 21:26

import myApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myApp', '0004_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='video/%y', validators=[myApp.validators.file_size])),
            ],
        ),
    ]
