# Generated by Django 5.0.5 on 2024-05-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
