# Generated by Django 5.0.5 on 2024-05-11 21:36

import django.core.validators
import django.db.models.deletion
import myApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myApp', '0006_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='workerProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(default='media/profile/default.jpg', upload_to='media/profile', verbose_name='profile')),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('workerId', models.AutoField(primary_key=True, serialize=False)),
                ('workerName', models.CharField(max_length=100, verbose_name='Student Name')),
                ('workerPhoneNo', models.CharField(max_length=112, unique=True, validators=[django.core.validators.RegexValidator(message='Enter phone number without +91', regex='^\\+?1?\\d{9,10}$')])),
                ('workerPhoto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myApp.workerprofile', verbose_name='worker profile')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='video/%y', validators=[myApp.validators.file_size])),
                ('workerProfile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myApp.workerprofile', verbose_name='worker Profile')),
            ],
        ),
    ]
