# Generated by Django 5.0.5 on 2024-05-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='workerPhoto',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='worker',
        ),
        migrations.DeleteModel(
            name='workerProfile',
        ),
    ]
