# Generated by Django 5.0.5 on 2024-05-12 13:15

import django.core.validators
import django.db.models.deletion
import myApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myApp', '0008_remove_worker_workerphoto_delete_video_delete_worker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='video/%y', validators=[myApp.validators.file_size])),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('workerId', models.AutoField(primary_key=True, serialize=False)),
                ('workerName', models.CharField(max_length=100, verbose_name='Worker Name')),
                ('workerPhoneNo', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter phone number without +91', regex='^\\+?1?\\d{9,10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='workerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='media/profile/default.jpg', upload_to='media/profile', verbose_name='profile')),
                ('workerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.worker', verbose_name='worker Id')),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='workerPhoto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.workerprofile', verbose_name='worker profile'),
        ),
    ]
