# Generated by Django 5.0.6 on 2024-05-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='workerPhoto',
        ),
    ]
