# Generated by Django 5.0.6 on 2024-05-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_remove_worker_workerphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='workerPhoneNo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
