# Generated by Django 5.0.6 on 2024-05-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_alter_worker_workerphoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='workerPhoneNo',
            field=models.CharField(max_length=20),
        ),
    ]
