# Generated by Django 4.2 on 2024-05-27 18:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0012_alter_worker_workerphoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('phone_num', models.CharField(max_length=112, unique=True, validators=[django.core.validators.RegexValidator(message='Enter phone number without +91', regex='^\\+?1?\\d{9,10}$')])),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='workerProfile',
        ),
    ]
