# Generated by Django 4.2 on 2024-05-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_supervisors_delete_workerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisors',
            name='user',
        ),
    ]
