# Generated by Django 4.2 on 2024-05-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_remove_supervisors_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisors',
            name='id',
        ),
        migrations.AddField(
            model_name='supervisors',
            name='supervisorId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supervisors',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Supervisor Name'),
        ),
    ]
